apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: federation
  namespace: openshift-operator-lifecycle-manager
spec:
  sourceType: grpc
  image: quay.io/openshift/federation-operator-registry