apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: federation
  namespace: openshift-operator-lifecycle-manager
spec:
  sourceType: grpc
  # Note, this image is not a real one. For development, use the
  # scripts/install-using-catalog-source.sh script to do a scripted installation
  # using images in an image registry you control.
  image: quay.io/openshift/federation-operator-registry:v4.0.0